# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-01 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190601_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barwith',
            name='doing',
        ),
        migrations.AddField(
            model_name='barcheckin',
            name='doing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Doing'),
        ),
    ]
