# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-01 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190601_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='bardrinking',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
