# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-01 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190601_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='barmeta',
            name='gay_friendly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='barmeta',
            name='sells_smokes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barmeta',
            name='sports_bar',
            field=models.BooleanField(default=False),
        ),
    ]
