# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-01 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190601_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='barmeta',
            name='near_transit',
            field=models.BooleanField(default=True),
        ),
    ]
