# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-01 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_barmeta_near_transit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarAlsoKnownAs',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bar')),
            ],
            options={
                'db_table': 'bar_also_known_as',
            },
        ),
        migrations.AddField(
            model_name='barmeta',
            name='historic',
            field=models.BooleanField(default=False),
        ),
    ]
