# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-01 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190601_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='baralsoknownas',
            name='closed_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
