# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-02 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_barmeta_non_alchohol_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='barmeta',
            name='local_beers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barmeta',
            name='takes_amex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barmeta',
            name='takes_discover',
            field=models.BooleanField(default=False),
        ),
    ]
