# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-02 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190602_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartenderreview',
            name='review',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
