# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-02 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_bartenderhot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartender',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gender'),
        ),
    ]
