# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-02 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190602_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='barmeta',
            name='local',
            field=models.BooleanField(default=False),
        ),
    ]
