# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-02 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_barmeta_first_calll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barmeta',
            old_name='first_calll',
            new_name='first_call',
        ),
    ]
