# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-02 21:59
from __future__ import unicode_literals
from django.db import migrations
from ..models.utils import insert_lookups


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190602_1434'),
    ]

    operations = [
        migrations.RunSQL("alter table gender drop column value"),
        migrations.RunPython(insert_lookups),
    ]
