# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-03 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_gender_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcheckin',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
