# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-03 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190603_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='value',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
