# Generated by Django 2.2.2 on 2019-06-04 00:18

import api.models.bar
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190603_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BarImage',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(max_length=255, upload_to=api.models.bar.image_upload_path)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
