# Generated by Django 2.2.2 on 2019-06-04 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190604_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barmeta',
            name='bar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Bar'),
        ),
    ]
