# Generated by Django 2.2.2 on 2019-06-04 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190604_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barmeta',
            name='atmosphere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Atmosphere'),
        ),
    ]
