# Generated by Django 2.2.2 on 2019-06-04 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20190604_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcheckin',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='barmeta',
            name='bar_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BarInfo'),
        ),
    ]
