# Generated by Django 2.2.2 on 2019-06-04 14:42

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20190604_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='barmeta',
            name='age_group',
        ),
        migrations.AddField(
            model_name='barmeta',
            name='age_group',
            field=models.ManyToManyField(blank=True, null=True, to='api.AgeGroup'),
        ),
    ]
