# Generated by Django 2.2.2 on 2019-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20190604_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barmeta',
            name='atmosphere',
        ),
        migrations.AddField(
            model_name='barmeta',
            name='atmosphere',
            field=models.ManyToManyField(blank=True, null=True, to='api.Atmosphere'),
        ),
        migrations.RemoveField(
            model_name='barmeta',
            name='bar_info',
        ),
        migrations.AddField(
            model_name='barmeta',
            name='bar_info',
            field=models.ManyToManyField(blank=True, null=True, to='api.BarInfo'),
        ),
        migrations.RemoveField(
            model_name='barmeta',
            name='bar_type',
        ),
        migrations.AddField(
            model_name='barmeta',
            name='bar_type',
            field=models.ManyToManyField(blank=True, null=True, to='api.BarType'),
        ),
        migrations.RemoveField(
            model_name='barmeta',
            name='happy_hour',
        ),
        migrations.AddField(
            model_name='barmeta',
            name='happy_hour',
            field=models.ManyToManyField(blank=True, to='api.BarHappyHour'),
        ),
        migrations.RemoveField(
            model_name='barmeta',
            name='popular_hours',
        ),
        migrations.AddField(
            model_name='barmeta',
            name='popular_hours',
            field=models.ManyToManyField(blank=True, to='api.BarPopularHours'),
        ),
    ]
