# Generated by Django 2.2.2 on 2019-06-04 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20190604_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barmeta',
            name='bar_type',
            field=models.ManyToManyField(blank=True, to='api.BarType'),
        ),
    ]
