# Generated by Django 2.2.2 on 2019-06-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190604_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barmeta',
            name='age_group',
            field=models.ManyToManyField(blank=True, to='api.AgeGroup'),
        ),
        migrations.AlterField(
            model_name='barmeta',
            name='bar_info',
            field=models.ManyToManyField(blank=True, to='api.BarInfo'),
        ),
    ]
