# Generated by Django 2.2.2 on 2019-06-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20190604_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barmeta',
            name='atmosphere',
            field=models.ManyToManyField(blank=True, to='api.Atmosphere'),
        ),
    ]
