# Generated by Django 2.2.2 on 2019-06-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20190604_1600'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barrating',
            table='db_rating',
        ),
    ]
