# Generated by Django 2.2.2 on 2019-06-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20190604_1805'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barrating',
            table='bar_rating',
        ),
    ]
