# Generated by Django 2.2.2 on 2019-06-08 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20190606_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bartenderschedule',
            name='bartender_bar',
        ),
        migrations.DeleteModel(
            name='BartenderBar',
        ),
        migrations.AddField(
            model_name='bartender',
            name='bar',
            field=models.ManyToManyField(blank=True, to='api.Bar'),
        ),
        migrations.AddField(
            model_name='bartenderschedule',
            name='bar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Bar'),
        ),
        migrations.AddField(
            model_name='bartenderschedule',
            name='bartender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Bartender'),
        ),
    ]
