# Generated by Django 2.2.2 on 2019-06-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20190608_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bartender',
            old_name='bar',
            new_name='bars',
        ),
    ]
