# Generated by Django 2.2.2 on 2019-06-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20190608_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartender',
            name='nickname',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
