# Generated by Django 2.2.2 on 2019-06-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20190608_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bartenderhot',
            name='user',
        ),
        migrations.AddField(
            model_name='bartenderhot',
            name='bartender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Bartender'),
            preserve_default=False,
        ),
    ]
