# Generated by Django 2.2.2 on 2019-06-10 17:44

import api.models.base
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20190608_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='BartenderHotVote',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hot', models.BooleanField()),
                ('bartender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bartender')),
            ],
            options={
                'db_table': 'bartender_hot_vote',
            },
            bases=(models.Model, api.models.base.CachedPropertiesMixin),
        ),
        migrations.DeleteModel(
            name='BartenderHot',
        ),
    ]
