# Generated by Django 2.2.2 on 2019-06-12 16:58

import api.models.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0047_auto_20190610_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contract_uploader',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('review_text', models.TextField()),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, api.models.base.CachedPropertiesMixin),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['object_id'], name='review_object__8eb6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='review_created_de4c36_idx'),
        ),
    ]
