# Generated by Django 2.2.2 on 2019-06-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20190612_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarReview',
        ),
    ]
