# Generated by Django 2.2.2 on 2019-06-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20190612_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_bar_types',
            field=models.ManyToManyField(related_name='favorite_bar_types', to='api.BarType'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_music_genres',
            field=models.ManyToManyField(related_name='favorite_music_genres', to='api.MusicGenre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_in_age_groups',
            field=models.ManyToManyField(related_name='interested_in_age_groups', to='api.AgeGroup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_in_genders',
            field=models.ManyToManyField(related_name='interested_in_genders', to='api.Gender'),
        ),
    ]
