# Generated by Django 2.2.2 on 2019-06-12 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blurb',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Gender'),
        ),
    ]
