# Generated by Django 2.2.2 on 2019-06-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20190612_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='USA', max_length=3, null=True),
        ),
    ]
