# Generated by Django 2.2.2 on 2019-06-12 22:02

import api.models.base
from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_profile_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationShipStatus',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'relationship_status',
            },
            bases=(models.Model, api.models.base.CachedPropertiesMixin),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='country',
            field=models.CharField(default='USA', max_length=3),
        ),
        migrations.AlterModelTable(
            name='neighborhood',
            table='neighborhood',
        ),
    ]
