# Generated by Django 2.2.2 on 2019-06-12 22:03

from django.db import migrations
from ..models.lookups import RelationshipStatus, RELATIONSHIP_STATUS

def add_relationship_status(apps, schema_editor):
    for status in RELATIONSHIP_STATUS:
        r = RelationShipStatus(name=status)
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20190612_2202'),
    ]

    operations = [
        migrations.RunPython(add_relationship_status)
    ]
