# Generated by Django 2.2.2 on 2019-06-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20190612_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RelationshipStatus'),
        ),
    ]
