# Generated by Django 2.2.2 on 2019-06-13 02:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20190613_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={},
        ),
        migrations.AlterField(
            model_name='bar',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RelationshipStatus'),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set(),
        ),
    ]
