# Generated by Django 2.2.2 on 2019-06-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20190613_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RelationshipStatus'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state_province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
